// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnphclflgtbcwinxrtjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNucGhjbGZsZ3RiY3dpbnhydGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTU1NzMsImV4cCI6MjA3MzU5MTU3M30._MMUdY7taIQQxW2wVYBN_-8GpsN9Cm9evxTDiS2xX1M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});